(function(){if(!google.nocsixjs&&google.timers&&google.timers.load.t)google.timers.load.t.xjses=(new Date).getTime();})();
(function(){google.isOpera=false;google.isIE=false;google.isSafari=false;
google.xhr=function(){var a=null;try{a=new XMLHttpRequest}catch(d){}return a};
google.getComputedStyle=function(a,d,b){var c=b?"":0;var e=document.defaultView&&document.defaultView.getComputedStyle(a,"");c=e.getPropertyValue(d);c=b?c:parseInt(c,10);return c};google.getHeight=function(a){return google.getComputedStyle(a,"height")};google.getWidth=function(a){return google.getComputedStyle(a,"width")};google.getPageOffsetTop=function(a){return a.offsetTop+(a.offsetParent?google.getPageOffsetTop(a.offsetParent):0)};
google.getPageOffsetLeft=function(a){return a.offsetLeft+(a.offsetParent?google.getPageOffsetLeft(a.offsetParent):0)};google.getPageOffsetStart=function(a){return google.getPageOffsetLeft(a)};google.getColor=function(a){return google.getComputedStyle(a,"color",true)};google.rhs=function(){};var f,g=location;
google.nav=function(a,d){try{var b=location.protocol+"//"+location.host;if((new RegExp("^("+b+")?/url\\?.*&rct=j(&|$)")).test(a))if(d){google.r=1;d.location.replace(a)}else{if(!f){f=document.createElement("iframe");f.style.display="none";google.append(f)}google.r=1;f.src=a}else g.href=a}catch(c){g.href=a}};google.append=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)};google.bind=function(a,d,b){a.addEventListener(d,b,false);};window.google.unbind=function(a,d,b){a.removeEventListener(d,b,false);};})();
(function(){var c=window,f=Object,h=google,i="push",j="length",k="propertyIsEnumerable",l="prototype",m="call";
function n(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof f)&&f[l].toString[m](a)=="[object Array]"||typeof a[j]=="number"&&typeof a.splice!="undefined"&&typeof a[k]!="undefined"&&!a[k]("splice"))return"array";if(!(a instanceof f)&&(f[l].toString[m](a)=="[object Function]"||typeof a[m]!="undefined"&&typeof a[k]!="undefined"&&!a[k]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[m]=="undefined")return"object";return b}
function o(a){return(new p).serialize(a)}function p(){}p[l].serialize=function(a){var b=[];this.a(a,b);return b.join("")};p[l].a=function(a,b){switch(typeof a){case "string":this.b(a,b);break;case "number":this.d(a,b);break;case "boolean":b[i](a);break;case "undefined":b[i]("null");break;case "object":if(a==null){b[i]("null");break}if(n(a)=="array"){this.c(a,b);break}this.e(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var q={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},r=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;p[l].b=function(a,b){b[i]('"',a.replace(r,function(g){if(g in q)return q[g];var d=g.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return q[g]=e+d.toString(16)}),'"')};p[l].d=function(a,b){b[i](isFinite(a)&&!isNaN(a)?a:"null")};
p[l].c=function(a,b){var g=a[j];b[i]("[");for(var d="",e=0;e<g;e++){b[i](d);this.a(a[e],b);d=","}b[i]("]")};p[l].e=function(a,b){b[i]("{");var g="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b[i](g);this.b(d,b);b[i](":");this.a(e,b);g=","}}b[i]("}")};c.google.stringify=o;if(c.JSON&&c.JSON.stringify&&navigator.userAgent.indexOf("Chrome")==-1)c.google.stringify=c.JSON.stringify;h.History={};var s=[],t="/";h.History.client=function(a){s[i](a);return s[j]-1};var u,v;function w(){var a=u.value;v=a?eval("("+a+")"):{}}function x(a,b){w();v[t]||(v[t]={});v[t][a]=b;u.value=h.stringify(v)}function y(a,b){return function(){x(a,b)}}var z=[];function A(){for(var a=0,b;b=z[a++];)b();z=[]}h.History.save=function(a,b){u?x(a,b):z[i](y(a,b))};
h.History.initialize=function(a){t=a;v=null;if(u=document.getElementById("hcache")){w();for(a=0;a<s[j];++a)v&&v[t]&&v[t][a]&&s[a][m](null,v[t][a]);A()}};})();
(function(){var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":google.isIE?"":0}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.bind(window,"resize",google.rhs);google.rein.push(e);})();
(function(){var f=0,g=[];google.fx={};google.fx.linear=function(a){return a};google.fx.easeOut=function(a){return 1-Math.pow(1-a,3)};google.fx.easeInAndOut=function(a){return(3-2*a)*a*a};google.fx.animate=function(a,d,e){for(var c=0,b;b=d[c++];){b[5]=b[5]==null?"px":b[5];b[4]=b[4]||google.fx.linear;h(b[0],b[1],b[2]+b[5])}g.push({b:a,a:e,d:google.time(),c:d});f=f||window.setInterval(i,15)};function i(){for(var a=0,d;d=g[a++];)j(d)||g.splice(--a,1);if(!g.length){window.clearInterval(f);f=0}}
function j(a){var d=google.time()-a.d;if(d>=a.b){for(var e=0,c;c=a.c[e++];)h(c[0],c[1],c[3]+c[5]);a.a&&a.a();return 0}else{for(e=0;c=a.c[e++];){var b=c[2]+(c[3]-c[2])*c[4](d/a.b);if(c[5]=="px")b=Math.round(b);h(c[0],c[1],b+c[5])}return 1}}
function h(a){for(var d=1;d<arguments.length;d+=2){var e=arguments[d],c=arguments[d+1],b=a.style;if(b&&e in b)b[e]=c;else if(e in a)a[e]=c;}return a}
google.fx.wrap=function(a){var d=document.createElement("div");a.parentNode.replaceChild(d,a);d.appendChild(a);return d};google.fx.unwrap=function(a){a.parentNode.parentNode.replaceChild(a,a.parentNode)};google.dstr.push(function(){window.clearInterval(f);f=0;g=[]});})();
(function(){var c=true,f=null,g=false,h=g,i,j,k,l="",n=f;var p=f;var q=f,r=f,s=-1,t,u,v,x,y,A,B,C=0,D=0,E=f,F=0;var G,H;var J;
function aa(){if(y){ba();Q();y.value=A.value="";window.clearTimeout(n);window.clearInterval(p);l=B="";n=q=r=f;s=-1;C=D=F=0;J=0;}}
var R=0,ca=new RegExp("^[\\s\\u1100-\\u11FF\\u3040-\\u30FF\\u3130-\\u318F\\u31F0-\\u31FF\\u3400-\\u4DBF\\u4E00-\\u9FFF\\uAC00-\\uD7A3\\uF900-\\uFAFF\\uFF65-\\uFFDC]+$");
function da(a,b,d,e,o){t=a;u=b;H=document.getElementsByTagName("body")[0];j=k=i=u.value;if(!b.init){google.bind(t,"submit",ea);u.setAttribute("autocomplete","off");google.bind(u,"blur",function(){R||Q();R=0});u.onkeypress=S;google.bind(u,"keyup",T);y=fa("aq","f");A=fa("oq",j);v=
document.createElement("table");v.cellSpacing=v.cellPadding="0";x=v.style;v.className="gac_m";t.appendChild(v);b.init=c}Q();U();if(!h){ga();h=c}B=["/complete/search?hl=",google.kHL,(d?"&ds="+d:""),(e?"&pq="+encodeURIComponent(e):"")].join("");j=k=i=u.value;J=ha(u);p=window.setInterval(function(){var m=u.value;m!=i&&V(0);i=m},10);
W();(new Image).src="http://clients1.google.com.tw/generate_204";}
function ga(){function a(e,o){b.push(e,"{",o,"}")}var b=[];a(".gac_m","cursor:default;border:1px solid #000;z-index:99;background:#fff;position:absolute;margin:0;font-size:17px");a(".gac_m td","line-height:22px");a(".gac_b","background:#36c;color:#fff");var d="padding-left:3px;white-space:nowrap;overflow:hidden;text-align:left;";a(".gac_c",d);a(".gac_d","padding:0 3px;white-space:nowrap;overflow:hidden;text-align:right;color:green;font-size:0.77em");
a(".gac_b td","color:#fff");a(".gac_e","padding:0 3px 2px;text-decoration:underline;text-align:right;color:#00c;font-size:0.77em;line-height:0.88em");b=b.join("");d=document.createElement("style");
d.setAttribute("type","text/css");document.getElementsByTagName("head")[0].appendChild(d);d.appendChild(document.createTextNode(b));}
function U(){if(v){x.left=ia(u,"offsetLeft")+"px";x.top=ia(u,"offsetTop")+u.offsetHeight-1+"px";x.width=u.offsetWidth+"px";}}function fa(a,b){var d=document.createElement("input");d.type="hidden";d.name=a;d.value=b;return t.appendChild(d)}
function S(a){var b=a.keyCode;if(b==27&&x&&x.visibility=="visible"){Q();X(j);a.cancelBubble=c;return a.returnValue=g}if(b==38||b==40){D++;D%3==1&&V(b);return g}}function T(a){a=a.keyCode;if(D==0&&!(a==38||a==40))V(a);D=0;}
function V(a){if(a==38||a==40){R=1;u.blur();window.setTimeout(function(){u.focus()},10)}if(u.value!=i){j=u.value;J=ha(u);A.value=j}a==40&&ja(s+1);a==38&&ja(s-1);U();if(l!=j&&!E)E=window.setTimeout(Q,500);i=u.value;i==""&&!n&&W()}function ka(){if(!F){if(r)r.className="gac_a";this.className="gac_b";r=this;for(var a=0,b;b=q[a];a++)b==r&&(s=a)}}
function ja(a){if(!l&&j){k="";W()}else if(!(j!=l||!n))if(!(!q||q.length<=0))if(x&&x.visibility=="visible"){var b=q.length-1;if(r)r.className="gac_a";if(a==b||a==-1){s=-1;X(j);u.focus();y.value="f"}else{if(a>b)a=0;else if(a<-1)a=b-1;s=a;r=q.item(a);r.className="gac_b";X(r.completeString);y.value=r.completeId}}else Y()}
function Q(){if(E){window.clearTimeout(E);E=f}x&&(x.visibility="hidden");}function Y(){x&&(x.visibility="visible");U();F=1}
function ba(){if(v){v.innerHTML="";}}
function la(a){C>0&&C--;if(!(!v||a[0]!=j)){if(E){window.clearTimeout(E);E=f}l=String(a[0]);ba();var d=g;for(var e=0,o;e<a[1].length;e++)if(o=a[1][e]){d=c;var m=v.insertRow(-1);m.onclick=function(){u.blur();
X(this.completeString);ea();t.onsubmit&&t.onsubmit()==g||t.submit();};m.onmousedown=Z;m.onmouseover=ka;m.onmousemove=function(){if(F){F=0;ka.call(this)}};m.completeString=
o[0];m.completeId=o[2];m.className="gac_a";var z=document.createElement("td");$(z,o[0]);z.className="gac_c";m.appendChild(z);var K=document.createElement("td");$(K,o[1]);K.className="gac_d";m.appendChild(K);}if(d){e=v.insertRow(-1);e.onmousedown=Z;w=document.createElement("td");w.colSpan=2;e.className="gac_e";e.appendChild(w);d=document.createElement("span");d.style.cursor="pointer";w.appendChild(d);$(d,"關閉");
d.onclick=function(){Q();l="";window.clearTimeout(n);n=f;y.value="x"}}s=-1;q=v.rows;(q&&q.length>0?Y:Q)()}}function ea(){Q();if(A.value!=u.value)y.value=q&&q.item(s)&&q.item(s).completeId;else{A.value="";if(C>=10)y.value="o"}}
function W(){if(k!=j&&j){C++;G&&H.removeChild(G);G=document.createElement("script");G.src=["http://clients1.google.com.tw",B,"&q=",encodeURIComponent(j),"&cp="+J].join("");H.appendChild(G);u.focus()}k=j;for(var a=100,
b=1;b<=(C-2)/2;++b)a*=2;a+=50;n=window.setTimeout(W,a)}function X(a){if(u)u.value=i=a}function ia(a,b){for(var d=0;a;){d+=a[b];a=a.offsetParent}return d}function $(a,b){a.appendChild(document.createTextNode(b))}
function Z(a){a.stopPropagation();return g}
function ha(a){var b=0,d=0;if(oa(a)){b=a.selectionStart;d=a.selectionEnd}return b&&d&&b==d?b:0}function oa(a){try{return typeof a.selectionStart=="number"}catch(b){return g}}
window.google.ac={i:da,h:la,u:X};google.bind(window,"resize",U);google.dstr.push(aa);})();
(function(){window.ManyBox={};var d,g,i=1,l=google.History.client(j);function m(a){for(var b in d)if(d[b].c&&a(d[b]))return}function n(a,b,c,e,f){this.c=a;this.i=b;this.B=e;this.o=f;this.q="/mbd?"+(b?"docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+e+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.l="";g[a]={r:0,D:this.e,i:this.i,h:0};this.n=0}n.prototype.append=function(a){this.l+="&"+a.join("&")};
function o(a,b){a.g.style.paddingTop=b+"px";a.g.style.display=a.g.innerHTML?"":"none";if(b>a.n)a.n=b}
function q(a){if(!a.A){a.A=1;a.d=document.getElementById("mbb"+a.c);a.j=0;a.a=document.getElementById("mbl"+a.c);a.m=a.a.getElementsByTagName("DIV")[0];a.p=a.a.getElementsByTagName("A")[0];a.z=a.p.innerHTML;a.o=a.o||a.z;a.m.title="按一下以取得詳細資訊。";a.a.F=function(b,c){var e=google.getPageOffsetStart(a.a),f=google.getPageOffsetTop(a.a);return b>e-5&&b<e+google.getWidth(a.a)+5&&c>f-5&&c<f+google.getHeight(a.a)+5};a.g=document.getElementById("mbf"+a.c);o(a,0);a.a.onmousedown=r(a);a.a.onclick=s(a);a.a.go=
function(){a.a.onmousedown();a.a.onclick()}}}function t(a){google.log("manybox",[a.j?"close":"open","&id=",a.c,"&docid=",a.i,"&mbtype=",a.B,a.l].join(""))}
function r(a){return function(){if(g[a.c].h)a.I++<3&&t(a);else{if(a.e.k)t(a);else{var b=google.xhr();if(b){b.open("GET",a.q+a.l+"&zx="+google.time());a.t=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(e){}if(!c&&!a.C){g[a.c].h=0;a.C=1;a.q+="&cad=retry";a.a.onmousedown()}else{a.u&&u(a);a.t=0}}};a.t=1;b.send(null)}}g[a.c].h=a.I=1}}}function s(a){return function(){g[a.c].h||a.a.onmousedown();(a.u=a.t)||u(a)}}
function v(a){if(!a.e.k){a.e.k="\x3cfont color\x3dred\x3e錯誤：\x3c/font\x3e 伺服器無法完成您的要求。  請在 30 秒後再試一次。";a.G=a.a.onclick;a.a.onclick=function(){i=0;u(a);i=1;a.b.parentNode.removeChild(a.b);g[a.c].h=a.e.k=a.v=0;a.a.onclick=a.G}}if(!a.v){a.v=1;var b=document.getElementById("res");a.H=b&&google.getPageOffsetStart(a.d)>google.getPageOffsetStart(b)+google.getWidth(b);a.b=document.createElement("div");o(a,0);a.b.style.position="absolute";a.b.style.paddingTop=a.b.style.paddingBottom="6px";a.b.style.display="none";a.b.className="med";b=document.createElement("div");
a.b.appendChild(b);b.className="std";b.innerHTML=a.e.k;a.g.parentNode.insertBefore(a.b,a.g)}}function j(a){i=0;ManyBox.init();m(function(b){if(b.i==a[b.c].i){b.e=a[b.c].D;a[b.c].r!=b.j&&u(b)}else a[b.c].h=0});g=a;i=1;google.History.save(l,g)}ManyBox.create=function(a,b,c,e,f){return new n(a,b,c,e,f)};ManyBox.register=function(a,b,c,e,f){return d[a]=ManyBox.create(a,b,c,e,f)};
google.bind(document,"click",function(a){a=a||window.event;for(var b=a.target||a.srcElement;b.parentNode;){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}m(function(c){if(c.a.F(a.clientX,a.clientY)){c.a.go();return 1}})});function w(){d={};g={};history.navigationMode=history.navigationMode&&"fast"}w();ManyBox.init=function(){m(q)};function x(a,b){a.b.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}n.prototype.insert=function(a){this.e.k=a};
function y(a){a.f=document.getElementById("mbcb"+a.c);var b=a.f&&a.f.getAttribute("mbopen");if(b){eval(b);a.onopen(a.f)}}function z(a){a.b.style.display="none";a.m.style.backgroundPosition="-91px -74px";a.p.innerHTML=a.z;a.j=g[a.c].r=0;google.History.save(l,g)}
function A(a,b,c,e,f){var k=c>0?150:75,h=google.time()-f;k=h<k&&i?h/k*c:e>1?c-10:c;h=Math.max(a.s,b+k);var p=h-a.s;x(a,p);a.d.style.height=h<0?0:p?h+"px":"";o(a,Math.max(0,p-5));google.rhs();Math.abs(k)<Math.abs(c)?window.setTimeout(function(){A(a,b,c,e-1,f)},30):window.setTimeout(function(){c<0?z(a):y(a);if(!google.isIE&&a.H)a.b.style.width="100px";a.b.style.position=a.d.style.height="";o(a,0);google.rhs();a.d.w=0},0)}
function u(a){a.u=0;if(!a.d.w){a.d.w=1;var b;if(a.j){if(b=a.f&&a.f.getAttribute("mbclose")){eval(b);a.onclose(a.f)}b=a.s-google.getHeight(a.d);a.g.style.display="none";o(a,a.n);a.b.style.position="absolute"}else{a.s=google.getHeight(a.d);v(a);o(a,0);a.n=0;m(function(c){c.m.title=""});a.m.style.backgroundPosition="-105px -74px";a.p.innerHTML=a.o;x(a,1);a.b.style.position="absolute";a.b.style.display="";a.j=g[a.c].r=1;google.History.save(l,g);b=a.b.offsetHeight}A(a,google.getHeight(a.d),b,google.isSafari?
2:1,google.time())}}google.dstr&&google.dstr.push(w);})();
(function(){var f=true,h=false,i,k;
function m(){i=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(i);k=i.sheet;}
google.addCSSRule=function(a,b){i||m();a=a+"{"+b+"}";k.insertRule(a,k.cssRules.length);};google.acrs=function(a){a=a.split(/{|}/);for(var b=1;b<a.length;b+=2)google.addCSSRule(a[b-1],a[b])};
var n=null,o=h,p=h,q=document.location.href.match("^.*?://[^/]*")[0],r,s;function t(a,b){s=document.getElementById("tbd");r=s.innerHTML=a;b||google.Toolbelt.toggle(null,null,f);google.j&&google.j.trap&&google.j.trap();google.isr&&google.isr.initialize&&google.isr.initialize()}var u=google.History.client(function(a){t(a.content,a.open==google.Toolbelt.isToolbeltOpen())}),x=google.History.client(function(a){google.acrs(a)});google.Toolbelt.ascrs=function(a){google.acrs(a);google.History.save(x,a)};
var y=[];google.Toolbelt.resetListeners=function(){y=[]};google.Toolbelt.registerToolbeltCallback=function(a){y.push(a)};function z(){for(var a=0,b;b=y[a++];)b()}google.Toolbelt.listeners=function(){return y};var A=/([?&])tbo=([^&]*)(&|$)/;function B(a){return(a=a.match(A))?a[2]:""}function C(a){a=B(a);return mbtb1.obd?a!="0":a!=""&&a!="0"}google.Toolbelt.setCurrentTbo=function(a){return D(a,google.Toolbelt.isToolbeltOpen())};
function D(a,b){var c=mbtb1.obd&&!B(a)?"":"1",d=mbtb1.obd?"0":"";b=b?c:d;return a.replace(A,"$1").replace(/&$/,"")+(b?"&tbo="+b:"")}
google.Toolbelt.updateTbo=function(){var a=google.Toolbelt.isToolbeltOpen();if(a!=C(google.base_href)){var b=document.getElementsByTagName("A");google.base_href=D(google.base_href,a);for(var c=0,d;d=b[c++];)if(d.href.match("^("+q+")?/(?!url|aclk|[^?]*$)")&&d!=n&&!d.href.match("[?&]tbo=u(&|$)")){d.href=D(d.href,a);}for(c=0;b=document.forms[c++];)if(b.action.match("/search$")){e=
d=0;for(var g;g=b.elements[e++];)if(g.name=="tbo"){d=1;if(a)g.value="1";else if(mbtb1.obd)g.value="0";else g.parentNode.removeChild(g)}if(!d){d=document.createElement("input");d.type="hidden";d.value=a?"1":"0";d.name="tbo";b.appendChild(d)}}}};function F(a){document.body.className=document.body.className.replace(/\btbo\b/,"")+(a?" tbo":"");google.Toolbelt.updateTbo();z()}google.Toolbelt.isToolbeltOpen=function(){return/\btbo\b/.test(document.body.className)};
google.Toolbelt.toggle=function(a,b,c){b=b||window.event;if(a)n=a;b&&b.stopPropagation();s=document.getElementById("tbd");if(!s)return f;r=s.innerHTML;b=s.getElementsByTagName("DIV").length>0;var d=google.Toolbelt.isToolbeltOpen();c=c||!!document.getElementById("tbt5")||mbtb1.na;if(d&&!p){google.Toolbelt.updateCalendarVisibility&&google.Toolbelt.updateCalendarVisibility(null);
G(h,c);google.log("toolbelt","0&ei="+google.kEI);o=f}else if(b){G(f,c);o&&google.log("toolbelt","1&ei="+google.kEI)}else{mbtb1.insert=t;var e=google.xhr();if(e){e.open("GET",[google.pageState?google.pageState.replace("#","/mbd?"):google.base_href.indexOf("/images?")==0?google.base_href.replace(/^\/images\?/,"/mbd?"):google.base_href.replace(/^\/search\?/,"/mbd?"),"&mbtype=29&resnum=1&tbo=1",mbtb1.tbs?"&tbs="+mbtb1.tbs:"","&docid=",mbtb1.docid,"&usg=",mbtb1.usg,"&zx=",google.time()].join(""),f);e.onreadystatechange=
function(){if(e.readyState==4&&e.status==200)try{eval(e.responseText)}catch(g){window.location.replace(a.href)}};e.send(null);p=f;G(f,c)}return h}google.History.save(u,{content:r,open:p||!d});p=h;google.isr&&google.isr.handleToolbeltToggle&&google.isr.handleToolbeltToggle();return h};function H(a){for(;a&&a.className!="tbt";)a=a.parentNode;return a}
google.Toolbelt.ctlClk=function(a,b,c){a=a||"cdr_opt";if(a=="cdr_opt"){c&&c.stopPropagation();}google.Toolbelt.maybeLoadCal&&google.Toolbelt.maybeLoadCal();b=b||"cdr_min";if(a=document.getElementById(a)){a.className="tbots";if(a=H(a)){c=0;for(var d;d=a.childNodes[c++];)if(d.className=="tbos")d.className="tbotu";(b=document.getElementById(b))&&b.focus()}}return h};
google.Toolbelt.cdrClk=google.Toolbelt.ctlClk;function I(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")}google.Toolbelt.cdrSbt=function(){return J("ctbs",{cdr_min:"cd_min",cdr_max:"cd_max"})};google.Toolbelt.clSbt=function(){return J("ltbs",{l_in:"cl_loc"})};google.Toolbelt.prcSbt=function(){J("prcbs",{prc_min:"pr_min",prc_max:"pr_max"});var a=document.getElementById("prc_frm");if(a){var b=document.getElementById("tsf");if(b)a.elements.q.value=b.elements.q.value}};
function J(a,b){if(a=document.getElementById(a))for(var c in b){var d=I(document.getElementById(c).value),e=new RegExp("("+b[c]+":)([^,]*)");a.value=a.value.replace(e,"$1"+d)}return f}google.Toolbelt.tbosClk=function(a){a=a||window.event;if((a=a.target||a.srcElement)&&a.className=="tbotu"){a.className="tbos";if(a=H(a))for(var b=0,c;c=a.childNodes[b++];)if(c.className=="tbots")c.className="tbou"}};
var K=google.fx.easeOut,L=[["tads","margin-left","marginLeft"],["res","margin-left","marginLeft"],["tbd","margin-left","marginLeft"],["mbEnd","width","width"],["tbt3","left","left"],["tbt8","left","left"],["tbt5","margin-left","marginLeft"]],M=h;function N(a){for(var b=0,c=0,d;d=L[c++];){var e=document.getElementById(d[0]);e&&a(e,d,b++)}}function O(){var a=[];N(function(b,c){c=c[1];a.push(c=="width"?b.offsetWidth:google.getComputedStyle(b,c))});return a}
function G(a,b){if(!M){var c=[],d=O(),e=google.getComputedStyle(s,"left",f),g=document.getElementById("cdr_min"),j=document.getElementById("cdr_max");if(g&&j){g.style.width=google.getComputedStyle(g,"width",f);j.style.width=google.getComputedStyle(j,"width",f)}F(a);google.isr&&google.isr.reflowResults&&google.isr.reflowResults();if(!b){if(a){e=google.getComputedStyle(s,"left",f);if(g&&j){g.style.width=google.getComputedStyle(g,"width",f);j.style.width=google.getComputedStyle(j,"width",f)}}var P=O();
N(function(v,w,E){c.push([v,w[2],d[E],P[E],K])});b=google.fx.wrap(s);b.style.position="absolute";b.style.overflow="hidden";b.style.left=e;s.style.display="block";s.style.position="static";M=f;google.fx.animate(a?400:200,c,function(){N(function(v,w){v.style[w[2]]=""});s.style.position="absolute";s.style.display="";google.fx.unwrap(s);if(g&&j){g.style.width="";j.style.width=""}M=h})}}};})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var e=window.gbar,g,k;function l(a){var b=window.encodeURIComponent&&(document.forms[0].q||"").value;if(b)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(c,d){return(d||"&")+"q="+encodeURIComponent(b)})}e.qs=l;function m(a,b,c,d,j,h){var f=document.getElementById(a),i=f.style;if(f){i.left=d?"auto":b+"px";i.right=d?b+"px":"auto";i.top=c+"px";i.visibility=k?"hidden":"visible";if(j&&h){i.width=j+"px";i.height=h+"px"}else{m(g,b,c,d,f.offsetWidth,f.offsetHeight);k=k?"":a}}}e.tg=function(a){a=a||window.event;var b=a.target||a.srcElement;a.cancelBubble=true;if(g!=null)n(b);else{a=document.createElement(Array.every||window.createPopup?"iframe":"div");a.frameBorder="0";a.src="#";g=b.parentNode.appendChild(a).id="gbs";document.onclick=e.close;n(b);e.alld&&e.alld(function(){var c=document.getElementById("gbli");if(c){var d=c.parentNode;d.removeChild(c);o(d)}})}};function p(a){var b,c=document.defaultView;if(c&&c.getComputedStyle){if(a=c.getComputedStyle(a,""))b=a.direction}else b=a.currentStyle?a.currentStyle.direction:a.style.direction;return b=="rtl"}function n(a){var b=0;if(a.className!="gb3")a=a.parentNode;var c=a.getAttribute("aria-owns")||"gbi",d=a.offsetWidth,j=a.offsetTop>20?46:24,h=false;do b+=a.offsetLeft||0;while(a=a.offsetParent);a=(document.documentElement.clientWidth||document.body.clientWidth)-b-d;d=p(document.body);if(c=="gbi"){var f=document.getElementById("gbi");e.alli&&e.alli(f);o(f);if(d){b=a;h=true}}else if(!d){b=a;h=true}k!=c&&e.close();m(c,b,j,h)}e.close=function(){k&&m(k,0,0)};function q(a,b){var c=a.firstChild?a.firstChild.className:"gb2";a.insertBefore(b,a.firstChild).className=c}function o(a){for(var b,c=window.navExtra;c&&(b=c.pop());)q(a,b)}})();;};
(function(){google.eggRequest=function(a){var b=document.createElement("SCRIPT");b.src="http://clients1.google.com/egg?ei="+google.kEI+"&cd="+a;google.append(b)};!google.neegg&&document.f&&document.f.btnI&&google.bind(document.f.btnI,"click",function(a){if(google.sn=="webhp"&&!google.neegg&&document.f.q.value==""){google.eggRequest("ifl");a.stopPropagation&&a.stopPropagation();a.cancelBubble=true;a.preventDefault&&a.preventDefault();return a.returnValue=false}});})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];
(function (){if(window.google){window.google.a={};window.google.c=1;function k(a,b,d){b=a.t[b];a=a.t.start;if(b&&(a||d)){if(d!=undefined)a=d;return b>a?b-a:a-b}}window.google.report=function(a,b,d){var f="";if(window.google.pt){f+="&srt="+window.google.pt;delete window.google.pt}var c=document.getElementById("csi");if(c){var e;if(window.google._bfr!=undefined)e=window.google._bfr;else{e=c.value;window.google._bfr=e;c.value=1}if(e)return""}if(a.b)f+="&"+a.b;if(window.parent!=window)f+="&wif=1";c=a.t;e=c.start;
var h=[];for(var g in c)g!="start"&&e&&h.push(g+"."+k(a,g));delete c.start;if(b)for(var i in b)f+="&"+i+"="+b[i];a=[d?d:"/csi","?v=3","&s="+(window.google.sn||"GWS")+"&action=",a.name,f,"&rt=",h.join(",")].join("");b=new Image;var j=window.google.c++;window.google.a[j]=b;b.onload=b.onerror=function(){delete window.google.a[j]};b.src=a;b=null;return a}};if(google.timers&&google.timers.load.t){if(!google.nocsixjs)google.timers.load.t.xjsee=google.time();window.setTimeout(function(){if(google.timers.load.t){google.timers.load.t.xjs=google.time();google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)}},0)};})();
